custom: ${file(./env.yml)}

service: amazon-goldbox

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: production
  environment:
    service: ${self:service}
    bucket: ${self:custom.bucket}
    goldbox_path: ${self:provider.stage}/goldbox/goldbox.json
    recent_path: ${self:provider.stage}/goldbox/recent.json
    rss_path: ${self:provider.stage}/goldbox/rss.xml
    rss_feed:  https://amazon.com/gp/goldbox
    affiliate_id: ${self:custom.affiliate_id}
    blacklist_path: ${self:custom.blacklist_path, ''}
    hashtags_path: ${self:custom.hashtags_path, ''}
    # accounts_path: ${self:custom.accounts_path, ''}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:provider.environment.bucket}/*"

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  goldbox:
    handler: goldbox.goldbox
    events:
      - schedule: cron(50 4,12,20 * * ? *)
  recent:
    handler: recent.recent
    events:
      - schedule: cron(55 4,12,20 * * ? *)
  rss:
    handler: rss.rss
    events:
      - schedule: rate(46 minutes)

plugins:
  - serverless-offline