custom: ${file(./env.yml)}

service: amazon-goldbox

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: production
  environment:
    service: ${self:service}
    bucket: ${self:custom.bucket}
    feeds_path: ${self:provider.stage}/rss/feeds.json
    active_path: ${self:provider.stage}/rss/active.json
    rss_path: ${self:provider.stage}/rss/rss.xml
    affiliate_id: ${self:custom.affiliate_id}
    blacklist_path: ${self:custom.blacklist_path, ''}
    hashtags_path: ${self:custom.hashtags_path, ''}
    accounts_path: ${self:custom.accounts_path, ''}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:provider.environment.bucket}/*"

functions:
  feeds:
    handler: feeds.feeds
    events:
      - schedule: cron(50 9 * * ? *)
  rss:
    handler: rss.rss
    events:
      - schedule: cron(0/55 * * * ? *)

plugins:
  - serverless-offline