custom: ${file(./env.yml)}

service: amazon-goldbox

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: production
  environment:
    service: ${self:service}
    bucket: ${self:custom.bucket}
    goldbox_path: ${self:provider.stage}/goldbox/goldbox.json
    recent_path: ${self:provider.stage}/goldbox/recent.json
    rss_feed:  http://rssfeeds.s3.amazonaws.com/goldbox
    affiliate_id: ${self:custom.affiliate_id}
    blacklist: ${self:custom.blacklist}
    hashtags: ${self:custom.hashtags}
    accounts: ${self:custom.accounts}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:provider.environment.bucket}/*"

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  goldbox:
    handler: goldbox.goldbox
    events:
      - schedule: cron(50 13 * * ? *)
  recent:
    handler: recent.recent
    events:
      - schedule: cron(55 13 * * ? *)

plugins:
  - serverless-offline